--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.1.24.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 17/12/2024 12:58:34 p. m.
-- Server version: 9.1.0
--

SET NAMES 'utf8';
